import { authorizeRelationship } from './access.js';
import { dateInZone } from './dates.js';
import { HttpError, uuid } from './validation.js';
import { requestHash } from './mutations.js';

const shape=row=>({sessionId:row.id,state:row.state,startedAt:row.started_at,clientFinishedAt:row.client_finished_at,receivedAt:row.received_at,occurrenceId:row.occurrence_id,relationshipId:row.relationship_id,revisionId:row.revision_id,scheduledDate:row.scheduled_date,timeZone:row.time_zone,unit:row.unit,prescriptionSnapshot:JSON.parse(row.prescription_json),actualWorkout:row.actual_json?JSON.parse(row.actual_json):null,summary:row.summary_json?JSON.parse(row.summary_json):null});
function summarize(prescription, actual, store, occurrenceId, sessionId){const target=(prescription.exercises||[]).reduce((n,e)=>n+(e.sets||[]).length,0);const done=(actual?.entries||[]).reduce((n,e)=>n+(e.sets||[]).filter(s=>s.done).length,0);const terminal=store.db.prepare("SELECT count(*) AS n FROM assigned_sessions WHERE occurrence_id=? AND id<>? AND state='finished'").get(occurrenceId,sessionId).n;return {targetSets:target,completedSets:done,classification:terminal?'extra':done===0?'zero':done<target?'partial':'completed'}}
export function sessionService(store,{now=()=>new Date(),beforeStart=()=>{}}={}){return {
 start(user,input){uuid(input.sessionId,'sessionId');const existing=store.db.prepare('SELECT * FROM assigned_sessions WHERE id=?').get(input.sessionId);if(existing){if(existing.client_id!==user.id||existing.occurrence_id!==input.occurrenceId)throw new HttpError(409,'SESSION_CONFLICT','This session ID is already in use');return shape(existing)}beforeStart();const row=store.db.prepare('SELECT o.*,r.trainer_id,r.client_id,r.status AS relationship_status,r.time_zone FROM workout_occurrences o JOIN client_relationships r ON r.id=o.relationship_id WHERE o.id=?').get(input.occurrenceId);authorizeRelationship(user,row&&{...row,id:row.relationship_id,status:row.relationship_status},'write-client');if(row.state!=='scheduled'||row.scheduled_date!==dateInZone(now(),row.time_zone))throw new HttpError(409,'SESSION_UNAVAILABLE','Only today’s scheduled workout can start');if(row.version!==input.expectedOccurrenceVersion)throw new HttpError(409,'VERSION_CONFLICT','Reload today’s workout before starting');const at=now().toISOString(),p=JSON.parse(row.prescription_override_json||row.prescription_json);store.transaction(()=>{store.db.prepare(`INSERT INTO assigned_sessions (id,occurrence_id,relationship_id,client_id,revision_id,state,started_at,scheduled_date,time_zone,unit,prescription_json) VALUES (?,?,?,?,?,'started',?,?,?,?,?)`).run(input.sessionId,row.id,row.relationship_id,user.id,row.revision_id,at,row.scheduled_date,row.time_zone,p.unit,JSON.stringify(p));store.db.prepare("UPDATE workout_occurrences SET state='started',version=version+1,updated_at=? WHERE id=?").run(at,row.id)})();return shape(store.db.prepare('SELECT * FROM assigned_sessions WHERE id=?').get(input.sessionId))},
 finish(user,input){uuid(input.sessionId,'sessionId');const row=store.db.prepare('SELECT * FROM assigned_sessions WHERE id=? AND client_id=?').get(input.sessionId,user.id);if(!row)throw new HttpError(404,'NOT_FOUND','Session not found');if(!['finished','abandoned'].includes(input.state))throw new HttpError(422,'VALIDATION_ERROR','Choose finished or abandoned');const actual=input.state==='finished'?(input.actualWorkout||{entries:[]}):null;const hash=requestHash({state:input.state,clientFinishedAt:input.clientFinishedAt||null,actualWorkout:actual});if(row.state!=='started'){if(row.result_hash===hash)return shape(row);throw new HttpError(409,'SESSION_CONFLICT','This session already has a different result')}const prescription=JSON.parse(row.prescription_json),summary=input.state==='finished'?summarize(prescription,actual,store,row.occurrence_id,row.id):{classification:'abandoned',targetSets:(prescription.exercises||[]).reduce((n,e)=>n+(e.sets||[]).length,0),completedSets:0};const at=now().toISOString();store.transaction(()=>{store.db.prepare('UPDATE assigned_sessions SET state=?,client_finished_at=?,received_at=?,actual_json=?,summary_json=?,result_hash=? WHERE id=?').run(input.state,input.clientFinishedAt||at,at,actual?JSON.stringify(actual):null,JSON.stringify(summary),hash,row.id);if(input.state==='finished')store.db.prepare("UPDATE workout_occurrences SET state='completed',version=version+1,updated_at=? WHERE id=?").run(at,row.occurrence_id);store.db.prepare(`INSERT INTO sync_receipts(client_id,assigned_result_received_at) VALUES (?,?) ON CONFLICT(client_id) DO UPDATE SET assigned_result_received_at=excluded.assigned_result_received_at`).run(user.id,at)})();return shape(store.db.prepare('SELECT * FROM assigned_sessions WHERE id=?').get(row.id))},
 list(user,relationshipId){const rel=store.db.prepare('SELECT * FROM client_relationships WHERE id=?').get(relationshipId);authorizeRelationship(user,rel,'read');return {items:store.db.prepare('SELECT * FROM assigned_sessions WHERE relationship_id=? ORDER BY started_at DESC').all(relationshipId).map(shape),nextCursor:null}}
}}
