import test from 'node:test'; import assert from 'node:assert/strict';
import { tempCoachingData, identityAuthority, fixedClock, testUsers } from './coaching-helpers.mjs';
import { openCoachingDb } from '../coaching/db.js'; import { profileService } from '../coaching/profiles.js'; import { invitationService, CONSENT_VERSION } from '../coaching/invitations.js';
import { occurrenceService } from '../coaching/occurrences.js'; import { sessionService } from '../coaching/sessions.js'; import { planService, validateWorkoutContent } from '../coaching/plans.js'; import { relationshipService } from '../coaching/relationships.js';

function fixture() { const identities=identityAuthority(); const store=openCoachingDb({dataDir:tempCoachingData(),identities}); const now=fixedClock(); const config={trainerIds:new Set([testUsers.trainerA.id])}; profileService(store,{config,now}).save(testUsers.trainerA.id,{expectedVersion:0,displayName:'Coach',businessTimeZone:'Asia/Kolkata'}); const inv=invitationService(store,{config,now}); const rel=inv.accept(inv.create(testUsers.trainerA.id).token,testUsers.clientA.id,{consentVersion:CONSENT_VERSION,confirmSharing:true}); const occ=occurrenceService(store,{now}); const plans=planService(store,{now,validateContent:(_k,v)=>validateWorkoutContent(v),afterPublish:occ.reconcile}); const p=plans.publish(testUsers.trainerA.id,{relationshipId:rel.id,kind:'workout',expectedVersion:0,content:{name:'Today',unit:'kg',days:[{id:'monday',name:'Monday',weekdays:[1],exercises:[{id:'squat',name:'Squat',mode:'reps',sets:[{reps:5,weight:60},{reps:5,weight:60}],restSec:120}]}]}}); const occurrence=store.db.prepare("SELECT * FROM workout_occurrences WHERE assignment_id=? AND scheduled_date='2026-09-07'").get(p.id); return {store,rel,occurrence,occurrences:occ,sessions:sessionService(store,{now}),relationships:relationshipService(store,{now,beforeEnd:occ.endRelationship})}; }

test('session start freezes targets and repeated completion is idempotent',()=>{ const fx=fixture(); const id='11111111-1111-4111-8111-111111111111'; const started=fx.sessions.start(testUsers.clientA,{sessionId:id,occurrenceId:fx.occurrence.id,expectedOccurrenceVersion:fx.occurrence.version}); assert.equal(started.prescriptionSnapshot.exercises[0].sets.length,2); assert.deepEqual(fx.sessions.start(testUsers.clientA,{sessionId:id,occurrenceId:fx.occurrence.id,expectedOccurrenceVersion:fx.occurrence.version}),started); const input={sessionId:id,state:'finished',clientFinishedAt:'2026-09-07T07:15:00.000Z',actualWorkout:{id,unit:'kg',entries:[{id:'squat',sets:[{w:60,r:5,done:true},{w:60,r:4,done:false}]}]}}; const done=fx.sessions.finish(testUsers.clientA,input); assert.equal(done.summary.classification,'partial'); assert.deepEqual(fx.sessions.finish(testUsers.clientA,input),done); assert.throws(()=>fx.sessions.finish(testUsers.clientA,{...input,actualWorkout:{...input.actualWorkout,entries:[]}}),e=>e.code==='SESSION_CONFLICT'); fx.store.close(); });

test('session start freezes the effective one-day prescription',()=>{ const fx=fixture(); const base=JSON.parse(fx.occurrence.prescription_json); base.dayName='Recovery Monday'; base.exercises[0].sets=[{reps:12,weight:30}]; const changed=fx.occurrences.customize(testUsers.trainerA,fx.occurrence.id,fx.occurrence.version,base); const started=fx.sessions.start(testUsers.clientA,{sessionId:'33333333-3333-4333-8333-333333333333',occurrenceId:fx.occurrence.id,expectedOccurrenceVersion:changed.version}); assert.equal(started.prescriptionSnapshot.dayName,'Recovery Monday'); assert.deepEqual(started.prescriptionSnapshot.exercises[0].sets,[{reps:12,weight:30}]); fx.store.close(); });

test('a started owner session can upload after unlink while trainer access ends',()=>{ const fx=fixture(); const id='22222222-2222-4222-8222-222222222222'; fx.sessions.start(testUsers.clientA,{sessionId:id,occurrenceId:fx.occurrence.id,expectedOccurrenceVersion:fx.occurrence.version}); fx.relationships.end(testUsers.clientA,fx.rel.id,fx.rel.version); const done=fx.sessions.finish(testUsers.clientA,{sessionId:id,state:'finished',actualWorkout:{id,unit:'kg',entries:[]}}); assert.equal(done.summary.classification,'zero'); assert.throws(()=>fx.sessions.list(testUsers.trainerA,fx.rel.id),e=>e.status===404); assert.equal(fx.sessions.list(testUsers.clientA,fx.rel.id).items.length,1); fx.store.close(); });
